### ISSUE TITLE
/2022/apr/30/a-gentle-introduction-to-ssr/ > "It's made up of just two files: index.html" - should be `client.html` 

### ISSUE THREAD

**Issue by ElijahLynn** [galvez/blog#2]
/2022/apr/30/a-gentle-introduction-to-ssr/ > "It's made up of just two files: index.html" - should be `client.html` 

Couldn't find the file, probably not pushed here yet, but /2022/apr/30/a-gentle-introduction-to-ssr/ > "It's made up of just two files: index.html" - should be `client.html`.

**Comment by galvez** [comment]
This is an outdated public repo of my blog. My real blog is running on another repo :)

But good catch! I'll correct it!

**Comment by ElijahLynn** [comment]
Cool cool!
